apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-java-app-dev
  namespace: openshift-gitops  # â† ArgoCD do OpenShift
  # ğŸ¯ CONFIGURAÃ‡ÃƒO PARA ARGOCD IMAGE UPDATER NATIVO
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-java-app=image-registry.openshift-image-registry.svc:5000/philippenunes-dev/my-java-app:latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/my-java-app.update-strategy: digest
    argocd-image-updater.argoproj.io/my-java-app.allow-tags: regexp:^latest$
spec:
  project: default

  source:
    repoURL: 'https://github.com/philippenunes/java-demo-openshift'
    targetRevision: main  
    path: k8s/overlays/dev  # ğŸ¯ Estrutura Kustomize
    kustomize: {}

  destination:
    server: 'https://kubernetes.default.svc'  # â† Mesmo cluster
    namespace: philippenunes-dev

  syncPolicy:
    # âœ… AutoSync habilitado para desenvolvimento
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true